### ISSUE TITLE
require() vs fs.readFile to read package.json

### ISSUE THREAD

**Issue by avelynhc** [sdthaker/Node-TILify#6]
Line 18 in index.js

When you use `const packageJson = require("../package.json");` to retrieve the package.json file instead of doing `fs.readFile(...)`, you don't have to parse it, which is an extra step.

**Comment by sdthaker** [comment]
Considering I'm using module imports for all the files in my project, I have to import package.json contents as 
`import packageJson from '../package.json' assert { type: 'json' };`

That being said, if I import the package.json contents and try to use it, I get the following warning:
`(node:62301) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time`

Now based on what it says, that it's an experimental feature, I wouldn't want to use an experimental feature in my code because if in future, this feature is removed from node, I'd have to fix the code again which I why I'm doing the extra step of parsing the contents of the package.json file for now.
